version: '2.3'

services:

  db:
    image: mariadb:10.3.4
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=magento2
      - MYSQL_ROOT_PASSWORD=root

  app:
    image: dannynimmo/magento2-php:7.1.15-0.1.0-dev.1
    restart: always
    volumes:
      - .:/var/www/html
      - "${HOME}/.composer:/root/.composer" # share your local composer directory for cache & auth
    depends_on:
      - db

  web:
    image: dannynimmo/magento2-nginx:1.12.2-0.1.0-dev.1
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    ports:
      - "8001:80"


volumes:
  db:
